#!/bin/bash
export RUNPROG="./stirap_oplattice"
export FILENAME_ENERGY="result/energies.dat"
export FILENAME_STATE="result/state.dat"
export T_WIN_INIT=0.0
export T_WIN_FINAL=7.00
export T_WIN_TOT=7.0
export T_WIN_INC=1.0
export LAMBDA_0=0.2
export OMEGA_F=10.896058668420753
export OMEGA_S=7.264038951734947
export NF=3
export NS=2
export U0=23.0
export KAPPA=7.287781
export STATECHOSEN=0

$RUNPROG $FILENAME_ENERGY $FILENAME_STATE $T_WIN_INIT $T_WIN_FINAL $T_WIN_TOT $T_WIN_INC $LAMBDA_0 $OMEGA_F $OMEGA_S $NF $NS $U0 $KAPPA $STATECHOSEN 
