#!/bin/bash
                                                                               #first line specifies shell
#BSUB -J optical_lattice_flq                                                   #name the job
#BSUB -o out.o%J                                                               #output->   out.o&ltjobID>
#BSUB -e err.o%J                                                               #error -> error.o&ltjobID>
#BSUB -M 1048576                                                               #1GB/task of memory
#BSUB -n 66 -W 0:35                                                           #No of CPUs and time 
#BSUB -q normal                                                                #Queue name
set echo                                                                                                                                                         #Echo all commands.
cd $LS_SUBCWD

export RUNPROG="./floquet_oplattice"
export FILENAME_ENERGY="result/energies_stirap_tonks_1_4_15_amp_0.2.dat"
export FILENAME_QUASI="result/quasienergies_tonks_1_4_15_amp_0.2.dat"
export TFIX_INIT=0.0
export TFIX_FINAL=36000.00
export TFIX_TOT=36000.0
export TFIX_INC=172.9942606170981 #100 cycles
export LAMBDA_0=0.2
export OMEGA_F=10.896058668420753
export OMEGA_S=7.264038951734947
export NF=3
export NS=2
export U0=23.0
export KAPPA=7.287781

export TAGA=40
export TAGB=54
export TAGC=55
export TAGD=60

export FILENAME_TAGA="result/floquetstate_tonks_1_4_15_amp_0.2_taga.dat"
export FILENAME_TAGB="result/floquetstate_tonks_1_4_15_amp_0.2_tagb.dat"
export FILENAME_TAGC="result/floquetstate_tonks_1_4_15_amp_0.2_tagc.dat"
export FILENAME_TAGD="result/floquetstate_tonks_1_4_15_amp_0.2_tagd.dat"

                                                                                                                                                   #cd to directory of submission
ibrun $RUNPROG $FILENAME_ENERGY $FILENAME_QUASI $TFIX_INIT $TFIX_FINAL $TFIX_TOT $TFIX_INC $LAMBDA_0 $OMEGA_F $OMEGA_S $NF $NS $U0 $KAPPA $TAGA $TAGB $TAGC $TAGD $FILENAME_TAGA $FILENAME_TAGB $FILENAME_TAGC $FILENAME_TAGD
                                                                                                                                                        #use ibrun for "pam -g mvapich_wrapper"
