(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* :Title: LegacyColors *)
(* :Context: LegacyColors` *)
(* :Author: Mark A. Caprio, Center for Theoretical Physics, Yale University *)
(* :Summary: Defines legacy colors except those which conflict with Mathematica 6 kernel colors. *)
(* :Copyright: Copyright 2007, Mark A. Caprio *)
(* :Package Version: 1.0 *)
(* :Mathematica Version: 6.0 *)
(* :History:
Originated .
V1.0, August 2007.
*)


BeginPackage["LegacyColors`"];


Unprotect[Evaluate[$Context<>"*"]];


KernelColors::usage="KernelColors contains a list of the 24 color names defined in the Mathematica 6 kernel.";NonkernelLegacyColors::usage="NonkernelLegacyColors contains a list of legacy color names excluding those defined in the Mathematica 6 kernel.";


KernelColors={
"Black", "Blue", "Brown", "Cyan", "Gray", "Green","Magenta", "Orange", "Pink", "Purple", "Red", "White", "Yellow",
"LightBlue", "LightBrown", "LightCyan", "LightGray", "LightGreen", "LightMagenta", "LightOrange", "LightPink", "LightPurple", "LightRed",
"LightYellow"
};
NonkernelLegacyColors=Complement[ColorData["Legacy", "Names"],KernelColors];


Scan[ToExpression,NonkernelLegacyColors];


Begin["`Private`"];


DefineColor[s_String]:=(Evaluate[ToExpression[s]]=ColorData["Legacy",s]);
Scan[DefineColor,NonkernelLegacyColors];


End[];


Protect[Evaluate[$Context<>"*"]];
Unprotect[Evaluate[$Context<>"$*"]];
EndPackage[];



